name: Build

on:
  workflow_call:
    inputs:
      node-version:
        default: 16.x
        required: false
        type: string
      force-build:
        default: false
        required: false
        type: boolean

jobs:
  file-changes:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.filter.outputs.files }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            files:
              - 'yarn.lock'
              - package.json
              - '.github/workflows/**'
              - 'parcels/**'

  build-parcels:
    needs:
      - file-changes
    if: needs.file-changes.outputs.files == 'true' || inputs.force-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Install Angular12
        working-directory: parcels/angular12
        run: yarn install --immutable

      - name: Install Angular13
        working-directory: parcels/angular13
        run: yarn install --immutable

      - name: Build Angular12
        working-directory: parcels/angular12
        run: yarn build

      - name: Build Angular13
        working-directory: parcels/angular13
        run: yarn build

      - name: Build
        run: yarn build

      - name: Save Build Cache
        id: save-build-cache
        uses: actions/cache/save@v3
        with:
          path: ./static
          key: ${{ runner.os }}-${{ github.sha }}-build

